---
abstract: 'Like grep, only keeps the stuff it filters out'
author:
  - 'Dominic Humphries <dominic@oneandoneis2.com>'
build_requires:
  Test::More: 0
configure_requires:
  ExtUtils::MakeMaker: 6.30
dynamic_config: 0
generated_by: 'Dist::Zilla version 4.300031, CPAN::Meta::Converter version 2.120921'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Array-KeepGrepped
requires:
  Exporter: 0
version: 2
